### ISSUE TITLE
manifest cannot be built while using S3 media storage

### ISSUE THREAD

**Issue by ekilfeather** [Daniel-KM/Omeka-S-module-IiifServer#21]
It appears that the ImageSize helper is not able to deal with media stored on an S3 bucket using the Any Cloud version 1.1.4 module. Is S3 currently supported? Stack trace below.

```
2020-03-02T16:18:51+00:00 ERR (3): Zend\View\Exception\RuntimeException: Failed to get image resolution: square/2297c23419bbb1c7b8b37d6a6877f221afbc689
a.jpg in /var/www/omeka-s/modules/IiifServer/src/View/Helper/ImageSize.php:42
Stack trace:
#0 [internal function]: IiifServer\View\Helper\ImageSize->__invoke(Object(Omeka\Api\Representation\MediaRepresentation), 'square')
#1 /var/www/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(IiifServer\View\Helper\ImageSize), Ar
ray)
#2 /var/www/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(606): Zend\View\Renderer\PhpRenderer->__call('imageSize', Array)
#3 /var/www/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(752): IiifServer\View\Helper\IiifManifest->_iiifThumbnail(Object(Omeka\Api\Repr
esentation\MediaRepresentation))
#4 /var/www/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(287): IiifServer\View\Helper\IiifManifest->_iiifCanvasImage(Object(Omeka\Api\Re
presentation\MediaRepresentation), 1)
#5 /var/www/omeka-s/modules/IiifServer/src/View/Helper/IiifManifest.php(72): IiifServer\View\Helper\IiifManifest->buildManifestItem(Object(Omeka\Api\Re
presentation\ItemRepresentation))
#6 /var/www/omeka-s/modules/IiifServer/src/Controller/PresentationController.php(156): IiifServer\View\Helper\IiifManifest->__invoke(Object(Omeka\Api\R
epresentation\ItemRepresentation))
#7 /var/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): IiifServer\Controller\PresentationController->itemAction()
#8 /var/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Z
end\Mvc\MvcEvent))
#9 /var/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\
MvcEvent), Object(Closure))
#10 /var/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object
(Closure), Object(Zend\Mvc\MvcEvent))
#11 /var/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\Php
Environment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 /var/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc
\MvcEvent), Object(Closure))
#14 /var/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(
Zend\Mvc\MvcEvent))
#15 /var/www/omeka-s/index.php(21): Zend\Mvc\Application->run()
#16 {main}
```

**Comment by Daniel-KM** [comment]
Thanks. It has been fixed in the last version (3.6.0), still in beta, but fully working (with the associated [ImageServer](https://github.com/Daniel-KM/Omeka-S-module-ImageServer)).
